"""
Country profile source data, part B (MLI-ZWE).

See py/country_profiles_data_a.py for field documentation. Merged by
py/build_country_profiles.py into ./reference/country_profiles.json.
"""

PROFILES_B = {
    "MLI": {
        "name": "Mali", "iso2": "ML", "subregion": "West Africa",
        "adm1": ["Bamako", "Bandiagara", "Bougouni", "Dioila", "Douentza", "Gao",
                 "Kayes", "Kidal", "Kita", "Koulikoro", "Koutiala", "Menaka",
                 "Mopti", "Nara", "Nioro", "San", "Segou", "Sikasso",
                 "Taoudenit", "Tombouctou"],
        "adm1_legacy": {
            "pre_2023": ["Bamako", "Gao", "Kayes", "Kidal", "Koulikoro", "Mopti",
                         "Segou", "Sikasso", "Tombouctou"],
        },
        "major_cities": ["Bamako", "Sikasso", "Mopti", "Gao", "Segou", "Kayes", "Timbuktu"],
        "neighbors": ["BFA", "CIV", "GIN", "MRT", "NER", "SEN", "DZA"],
        "search_languages": ["fr", "en"],
        "disease_terms": ["cholera", "diarrhee aqueuse aigue"],
        "health_domains": ["sante.gov.ml"],
        "season": "Niger river corridor (Mopti, Tombouctou, Gao); rainy season Jul-Sep; conflict-disrupted surveillance in north",
    },
    "MOZ": {
        "name": "Mozambique", "iso2": "MZ", "subregion": "Southern Africa",
        "adm1": ["Cabo Delgado", "Gaza", "Inhambane", "Manica", "Maputo", "Maputo City",
                 "Nampula", "Niassa", "Sofala", "Tete", "Zambezia"],
        "major_cities": ["Maputo", "Matola", "Beira", "Nampula", "Quelimane", "Pemba", "Tete"],
        "neighbors": ["MWI", "ZAF", "SWZ", "TZA", "ZMB", "ZWE"],
        "search_languages": ["pt", "en"],
        "disease_terms": ["colera", "diarreia aguda aquosa", "surto de colera"],
        "health_domains": ["misau.gov.mz", "ins.gov.mz"],
        "season": "Cyclone/flood-driven epidemics (Idai 2019, Freddy 2023); rainy season Nov-Apr; DNSP publishes cholera bulletins",
    },
    "MRT": {
        "name": "Mauritania", "iso2": "MR", "subregion": "West Africa",
        "adm1": ["Adrar", "Assaba", "Brakna", "Dakhlet Nouadhibou", "Gorgol", "Guidimaka",
                 "Hodh Ech Chargui", "Hodh El Gharbi", "Inchiri", "Nouakchott Nord",
                 "Nouakchott Ouest", "Nouakchott Sud", "Tagant", "Tiris Zemmour", "Trarza"],
        "major_cities": ["Nouakchott", "Nouadhibou", "Rosso", "Kaedi", "Kiffa", "Nema"],
        "neighbors": ["DZA", "MLI", "SEN"],
        "search_languages": ["fr", "ar", "en"],
        "disease_terms": ["cholera", "diarrhee aqueuse aigue",
                          "\u0627\u0644\u0643\u0648\u0644\u064a\u0631\u0627",
                          "\u0627\u0644\u0625\u0633\u0647\u0627\u0644 \u0627\u0644\u0645\u0627\u0626\u064a \u0627\u0644\u062d\u0627\u062f"],
        "health_domains": ["sante.gov.mr"],
        "season": "Senegal river valley (Trarza, Gorgol, Brakna); shares epidemiology with Senegal/Mali",
    },
    "MWI": {
        "name": "Malawi", "iso2": "MW", "subregion": "East Africa",
        "adm1": ["Balaka", "Blantyre", "Chikwawa", "Chiradzulu", "Chitipa", "Dedza", "Dowa",
                 "Karonga", "Kasungu", "Likoma", "Lilongwe", "Machinga", "Mangochi",
                 "Mchinji", "Mulanje", "Mwanza", "Mzimba", "Neno", "Nkhata Bay",
                 "Nkhotakota", "Nsanje", "Ntcheu", "Ntchisi", "Phalombe", "Rumphi",
                 "Salima", "Thyolo", "Zomba"],
        "major_cities": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Karonga", "Nsanje"],
        "neighbors": ["MOZ", "TZA", "ZMB"],
        "search_languages": ["en", "ny"],
        "disease_terms": ["cholera", "acute watery diarrhoea", "kolera"],
        "health_domains": ["health.gov.mw", "phim.health.gov.mw"],
        "season": ("Lake Malawi shoreline and Shire valley (Nsanje, Chikwawa, "
                   "Karonga); rainy season Nov-Apr, but the 2022-23 epidemic (largest "
                   "recorded) persisted through the dry season - a strict seasonal "
                   "filter will under-search it"),
    },
    "NAM": {
        "name": "Namibia", "iso2": "NA", "subregion": "Southern Africa",
        "adm1": ["Erongo", "Hardap", "Karas", "Kavango East", "Kavango West", "Khomas",
                 "Kunene", "Ohangwena", "Omaheke", "Omusati", "Oshana", "Oshikoto",
                 "Otjozondjupa", "Zambezi"],
        "major_cities": ["Windhoek", "Walvis Bay", "Swakopmund", "Oshakati", "Rundu", "Katima Mulilo"],
        "neighbors": ["AGO", "BWA", "ZAF", "ZMB"],
        "search_languages": ["en", "af"],
        "disease_terms": ["cholera", "acute watery diarrhoea"],
        "health_domains": ["mhss.gov.na"],
        "season": "Northern regions bordering Angola (Kunene, Omusati, Ohangwena); flood-linked",
    },
    "NER": {
        "name": "Niger", "iso2": "NE", "subregion": "West Africa",
        "adm1": ["Agadez", "Diffa", "Dosso", "Maradi", "Niamey", "Tahoua", "Tillaberi", "Zinder"],
        "major_cities": ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua", "Diffa"],
        "neighbors": ["BEN", "BFA", "TCD", "MLI", "NGA", "DZA", "LBY"],
        "search_languages": ["fr", "en", "ha"],
        "disease_terms": ["cholera", "diarrhee aqueuse aigue"],
        "health_domains": ["sante.gouv.ne"],
        "season": "Niger river valley and Nigeria border (Maradi, Zinder, Dosso, Tahoua); rainy season Jun-Sep",
    },
    "NGA": {
        "name": "Nigeria", "iso2": "NG", "subregion": "West Africa",
        "adm1": ["Abia", "Adamawa", "Akwa Ibom", "Anambra", "Bauchi", "Bayelsa", "Benue",
                 "Borno", "Cross River", "Delta", "Ebonyi", "Edo", "Ekiti", "Enugu",
                 "Federal Capital Territory", "Gombe", "Imo", "Jigawa", "Kaduna", "Kano",
                 "Katsina", "Kebbi", "Kogi", "Kwara", "Lagos", "Nasarawa", "Niger", "Ogun",
                 "Ondo", "Osun", "Oyo", "Plateau", "Rivers", "Sokoto", "Taraba", "Yobe",
                 "Zamfara"],
        "major_cities": ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt", "Maiduguri",
                         "Kaduna", "Benin City"],
        "neighbors": ["BEN", "CMR", "TCD", "NER"],
        "search_languages": ["en", "ha"],
        "disease_terms": ["cholera", "acute watery diarrhoea"],
        "health_domains": ["health.gov.ng", "ncdc.gov.ng"],
        "season": "NCDC publishes weekly cholera sitreps; north-east conflict states (Borno, Yobe, Adamawa) and Lagos; rainy season Jun-Oct",
    },
    "RWA": {
        "name": "Rwanda", "iso2": "RW", "subregion": "East Africa",
        "adm1": ["Kigali", "Eastern Province", "Northern Province", "Southern Province",
                 "Western Province"],
        "major_cities": ["Kigali", "Butare", "Gisenyi", "Ruhengeri", "Rusizi", "Rubavu"],
        "neighbors": ["BDI", "COD", "TZA", "UGA"],
        "search_languages": ["en", "fr", "rw"],
        "disease_terms": ["cholera", "diarrhee aqueuse aigue"],
        "health_domains": ["moh.gov.rw", "rbc.gov.rw"],
        "season": "Lake Kivu shoreline (Rubavu, Rusizi) with DRC cross-border importation",
    },
    "SEN": {
        "name": "Senegal", "iso2": "SN", "subregion": "West Africa",
        "adm1": ["Dakar", "Diourbel", "Fatick", "Kaffrine", "Kaolack", "Kedougou", "Kolda",
                 "Louga", "Matam", "Saint-Louis", "Sedhiou", "Tambacounda", "Thies", "Ziguinchor"],
        "major_cities": ["Dakar", "Touba", "Thies", "Kaolack", "Saint-Louis", "Ziguinchor"],
        "neighbors": ["GMB", "GIN", "GNB", "MLI", "MRT"],
        "search_languages": ["fr", "en"],
        "disease_terms": ["cholera", "diarrhee aqueuse aigue"],
        "health_domains": ["sante.gouv.sn"],
        "season": "Touba Magal mass gathering historically amplified epidemics; rainy season Jul-Oct",
    },
    "SLE": {
        "name": "Sierra Leone", "iso2": "SL", "subregion": "West Africa",
        "adm1": ["Eastern Province", "Northern Province", "North West Province",
                 "Southern Province", "Western Area"],
        "major_cities": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu", "Port Loko"],
        "neighbors": ["GIN", "LBR"],
        "search_languages": ["en"],
        "disease_terms": ["cholera", "acute watery diarrhoea"],
        "health_domains": ["mohs.gov.sl"],
        "season": "Freetown coastal slums; rainy season May-Oct; 2012 major epidemic",
    },
    "SOM": {
        "name": "Somalia", "iso2": "SO", "subregion": "East Africa",
        "adm1": ["Awdal", "Bakool", "Banaadir", "Bari", "Bay", "Galguduud", "Gedo", "Hiiraan",
                 "Jubbada Dhexe", "Jubbada Hoose", "Mudug", "Nugaal", "Sanaag",
                 "Shabeellaha Dhexe", "Shabeellaha Hoose", "Sool", "Togdheer",
                 "Woqooyi Galbeed"],
        "major_cities": ["Mogadishu", "Hargeisa", "Kismayo", "Baidoa", "Bosaso", "Beledweyne"],
        "neighbors": ["DJI", "ETH", "KEN"],
        "search_languages": ["en", "so", "ar"],
        "disease_terms": ["cholera", "acute watery diarrhoea", "AWD", "daacuunka",
                          "\u0627\u0644\u0643\u0648\u0644\u064a\u0631\u0627"],
        "health_domains": ["moh.gov.so"],
        "season": "Endemic; Shabelle/Juba riverine districts and IDP camps; drought and flood cycles; reported as AWD/cholera jointly",
    },
    "SSD": {
        "name": "South Sudan", "iso2": "SS", "subregion": "East Africa",
        "adm1": ["Central Equatoria", "Eastern Equatoria", "Jonglei", "Lakes",
                 "Northern Bahr el Ghazal", "Unity", "Upper Nile", "Warrap",
                 "Western Bahr el Ghazal", "Western Equatoria", "Abyei",
                 "Greater Pibor", "Ruweng"],
        "major_cities": ["Juba", "Malakal", "Wau", "Bentiu", "Bor", "Renk", "Aweil"],
        "neighbors": ["CAF", "COD", "ETH", "KEN", "SDN", "UGA"],
        "search_languages": ["en", "ar"],
        "disease_terms": ["cholera", "acute watery diarrhoea",
                          "\u0627\u0644\u0643\u0648\u0644\u064a\u0631\u0627"],
        "health_domains": ["moh.gov.ss"],
        "season": "Nile corridor, PoC/IDP sites, Renk transit centres; 2024-25 epidemic; conflict-disrupted surveillance",
    },
    "SWZ": {
        "name": "Eswatini", "iso2": "SZ", "subregion": "Southern Africa",
        "adm1": ["Hhohho", "Lubombo", "Manzini", "Shiselweni"],
        "major_cities": ["Mbabane", "Manzini", "Lobamba", "Siteki", "Nhlangano"],
        "neighbors": ["MOZ", "ZAF"],
        "search_languages": ["en", "ss"],
        "disease_terms": ["cholera", "acute watery diarrhoea"],
        "health_domains": ["gov.sz"],
        "season": "Rare; importation risk from Mozambique and South Africa",
    },
    "TCD": {
        "name": "Chad", "iso2": "TD", "subregion": "Central Africa",
        "adm1": ["Barh-El-Gazel", "Batha", "Borkou", "Chari-Baguirmi", "Ennedi-Est",
                 "Ennedi-Ouest", "Guera", "Hadjer-Lamis", "Kanem", "Lac",
                 "Logone Occidental", "Logone Oriental", "Mandoul", "Mayo-Kebbi Est",
                 "Mayo-Kebbi Ouest", "Moyen-Chari", "N'Djamena", "Ouaddai", "Salamat",
                 "Sila", "Tandjile", "Tibesti", "Wadi Fira"],
        "major_cities": ["N'Djamena", "Moundou", "Sarh", "Abeche", "Bongor", "Adre"],
        "neighbors": ["CMR", "CAF", "LBY", "NER", "NGA", "SDN"],
        "search_languages": ["fr", "ar", "en"],
        "disease_terms": ["cholera", "diarrhee aqueuse aigue",
                          "\u0627\u0644\u0643\u0648\u0644\u064a\u0631\u0627",
                          "\u0627\u0644\u0625\u0633\u0647\u0627\u0644 \u0627\u0644\u0645\u0627\u0626\u064a \u0627\u0644\u062d\u0627\u062f"],
        "health_domains": ["sante.imedia235.net"],
        "season": "Lake Chad basin and Sudan border refugee influx (Ouaddai, Sila); 2025 epidemic linked to Sudan crisis; rainy season Jun-Sep",
    },
    "TGO": {
        "name": "Togo", "iso2": "TG", "subregion": "West Africa",
        "adm1": ["Centrale", "Grand Lome", "Kara", "Maritime", "Plateaux", "Savanes"],
        "major_cities": ["Lome", "Sokode", "Kara", "Kpalime", "Atakpame"],
        "neighbors": ["BEN", "BFA", "GHA"],
        "search_languages": ["fr", "en"],
        "disease_terms": ["cholera", "diarrhee aqueuse aigue"],
        "health_domains": ["sante.gouv.tg"],
        "season": "Lome coastal/lagoon foci in Maritime region; rainy season Apr-Jul",
    },
    "TZA": {
        "name": "Tanzania", "iso2": "TZ", "subregion": "East Africa",
        "adm1": ["Arusha", "Dar es Salaam", "Dodoma", "Geita", "Iringa", "Kagera", "Katavi",
                 "Kigoma", "Kilimanjaro", "Lindi", "Manyara", "Mara", "Mbeya", "Morogoro",
                 "Mtwara", "Mwanza", "Njombe", "Pemba North", "Pemba South", "Pwani",
                 "Rukwa", "Ruvuma", "Shinyanga", "Simiyu", "Singida", "Songwe", "Tabora",
                 "Tanga", "Zanzibar North", "Zanzibar South and Central", "Zanzibar Urban West"],
        "major_cities": ["Dar es Salaam", "Mwanza", "Dodoma", "Arusha", "Zanzibar City", "Kigoma"],
        "neighbors": ["BDI", "COD", "KEN", "MWI", "MOZ", "RWA", "UGA", "ZMB"],
        "search_languages": ["en", "sw"],
        "disease_terms": ["cholera", "kipindupindu", "acute watery diarrhoea"],
        "health_domains": ["www.moh.go.tz"],
        "season": "Lake Victoria and Tanganyika basins, Dar es Salaam, Zanzibar; rains Mar-May and Oct-Dec",
    },
    "UGA": {
        "name": "Uganda", "iso2": "UG", "subregion": "East Africa",
        # Uganda MoH and UNIPH report by DISTRICT, so districts are the useful
        # unit here. The four ISO first-level regions are kept separately rather
        # than mixed into the same list - mixing levels made agents emit some
        # AFR::UGA::<region> and some AFR::UGA::<district> codes, which collide
        # on aggregation and create exactly the double-counting risk CLAUDE.md warns about.
        "adm1_level": "district",
        "adm1": ["Kampala", "Wakiso", "Hoima", "Kikuube", "Kasese", "Bundibugyo",
                 "Ntoroko", "Buliisa", "Nebbi", "Pakwach", "Arua", "Madi Okollo",
                 "Terego", "Koboko", "Yumbe", "Obongi", "Adjumani", "Moyo", "Zombo",
                 "Amudat", "Moroto", "Nakapiripirit", "Nabilatuk", "Kaabong",
                 "Kotido", "Napak", "Namayingo", "Busia", "Mayuge", "Bugiri",
                 "Buikwe", "Mbale", "Tororo", "Kyotera", "Rakai", "Isingiro",
                 "Kayunga", "Nakasongola"],
        "adm1_regions": ["Central Region", "Eastern Region", "Northern Region",
                         "Western Region"],
        "major_cities": ["Kampala", "Gulu", "Mbarara", "Jinja", "Arua", "Mbale"],
        "neighbors": ["COD", "KEN", "RWA", "SSD", "TZA"],
        "search_languages": ["en", "sw"],
        "disease_terms": ["cholera", "acute watery diarrhoea"],
        "health_domains": ["health.go.ug", "uniph.go.ug"],
        "season": "Lake Albert/Edward fishing communities, Karamoja, refugee settlements (Bidibidi, Adjumani); rains Mar-May, Sep-Nov",
    },
    "ZAF": {
        "name": "South Africa", "iso2": "ZA", "subregion": "Southern Africa",
        "adm1": ["Eastern Cape", "Free State", "Gauteng", "KwaZulu-Natal", "Limpopo",
                 "Mpumalanga", "North West", "Northern Cape", "Western Cape"],
        "adm1_legacy": {
            # The 1980-82 epidemic is recorded against the four pre-1994
            # provinces and the homelands.
            "pre_1994": ["Transvaal", "Natal", "Cape Province", "Orange Free State",
                         "KwaZulu", "Transkei", "Bophuthatswana", "Venda", "Ciskei"],
        },
        "major_cities": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth",
                         "Bloemfontein", "Hammanskraal"],
        "neighbors": ["BWA", "LSO", "MOZ", "NAM", "SWZ", "ZWE"],
        "search_languages": ["en", "af"],
        "disease_terms": ["cholera", "acute watery diarrhoea"],
        "health_domains": ["health.gov.za", "nicd.ac.za"],
        "season": "NICD publishes outbreak reports; 2000-01 KZN epidemic, 2023 Hammanskraal outbreak; mostly imported cases otherwise",
    },
    "ZMB": {
        "name": "Zambia", "iso2": "ZM", "subregion": "Southern Africa",
        "adm1": ["Central", "Copperbelt", "Eastern", "Luapula", "Lusaka", "Muchinga",
                 "Northern", "North-Western", "Southern", "Western"],
        "major_cities": ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Livingstone", "Chipata", "Nchelenge"],
        "neighbors": ["AGO", "BWA", "COD", "MWI", "MOZ", "NAM", "TZA", "ZWE"],
        "search_languages": ["en"],
        "disease_terms": ["cholera", "acute watery diarrhoea"],
        "health_domains": ["moh.gov.zm", "www.znphi.co.zm"],
        "season": "Lusaka peri-urban (Kanyama, Chawama) and Lake Mweru/Tanganyika fishing camps; rainy season Nov-Apr; 2023-24 major epidemic",
    },
    "ZWE": {
        "name": "Zimbabwe", "iso2": "ZW", "subregion": "Southern Africa",
        "adm1": ["Bulawayo", "Harare", "Manicaland", "Mashonaland Central",
                 "Mashonaland East", "Mashonaland West", "Masvingo",
                 "Matabeleland North", "Matabeleland South", "Midlands"],
        "major_cities": ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru", "Kadoma", "Beitbridge"],
        "neighbors": ["BWA", "MOZ", "ZAF", "ZMB"],
        "search_languages": ["en", "sn"],
        "disease_terms": ["cholera", "acute watery diarrhoea"],
        "health_domains": ["mohcc.gov.zw"],
        "season": "2008-09 epidemic (~98k cases) is the reference event; Harare (Budiriro, Glen View) and Manicaland; rainy season Nov-Mar",
    },
}
